#!/bin/bash



lsc()
{
if [ -e ".sc" ]; then
	
	for i in *
	do
	echo sth
		if [ -e $i/$USER.start ] && [ ! -e $i/$USER.end ]; then
			echo  "niedokonczyles : " $i 
			
			for d in $i/*
			do
				if [ ! -e $d.$USER.watched  ]; then
					echo $d
				fi
			done
		fi
	done
	
	for i in *
	do
		if [ ! -e $i/$USER.end ]; then
			echo  $i 
		fi
	done
else
	for i in *
	do
		echo $i
	done 
fi
}

lsc2()
{
	old_color="01;34"
	new_color="01;40"
	`sed -i s/$old_color/$new_color/ ~/.dircolors`
	for i in *
	do
		if [ -e $i/$USER.start ] && [ ! -e $i/$USER.end ]; then
			echo $i
		fi	
	done
	exec bash
	
	
	old_color=$new_color
	new_color="01;45"
	
	`sed -i s/$old_color/$new_color/ ~/.dircolors`
	for i in *
	do
		if [ ! -e $i/$USER.end ]; then
			echo $i	
		fi
	done
	exec bash
	
	old_color=$new_color
	new_color="01;34"
	`sed -i s/$old_color/$new_color/ ~/.dircolors`
}
