#!/bin/bash

lsc()
{
	for i in *
	do
		if [ -e $i/$USER.start ]; then
			echo -e "niedokonczyles : " $i \n
		else
			echo -e $i \n
		fi
	done
	
	for i in *
	do
		if [ ! -e $i/$USER.end ]; then
			echo -e $i \n
		fi
	done
}
