#!/bin/bash

touch $USER.start

while getopts ":v" args; do

	if [ $args = 'v' ]; then
		for i in *
		do
			if [ $i != *.start] &&[ $i != *.end ] ]
				vlc $i
			fi
		done
	else
		for i in *
		do
			if [ $i != *.start] &&[ $i != *.end ] ]
				mplayer $i
			fi
		done
	fi

done

touch $USER.end
