#!/bin/bash

#touch $USER.start

getopts ":v" args

if [ $args = "v" ]; then
	for i in * 
	do
		if [ ".start" < "$i" ]; then
			vlc $i
			touch $i.$USER.watched
		fi
	done
else
	for i in * 
	do
		if [ ".start" > "$i" ]; then
			if [ ! -e "$i.$USER.watched" ]; then
#				mplayer $i
				echo $i
#				touch $i.$USER.watched
			fi
		fi
	done
fi

#touch $USER.end
