#!/bin/bash

index=0
last=0	

# First case: we have started the series and last video number is stored in $USER.start 

if [ -e $USER.start ]; then
	
	last=`cat $USER.start`
	for i in *
	do
		substring=`echo $i| cut -d'.' -f 2`
		if  [ "$substring" != "start" ] && [ "$substring" != "end" ]; then # excluding other users .end || .start files
			if [ "$index" -ge "$last" ]; then
					array[index]=$i
			fi
			let index=index+1
		fi
	done	
	
else

# Second case: we havent started the series

	for i in *
	do
		substring=`echo $i| cut -d'.' -f 2`
		if  [ "$substring" != "start" ] && [ "$substring" != "end" ]; then
			array[index]=$i
			let index=index+1
		fi
	done

fi

touch $USER.start
echo "0" > $USER.start # preventing crash when not watching whole first video

last_element="${#array[@]}"
let current_element=$last+2
for i in ${array[@]} 
do
	mplayer -msglevel all=0 $i
	echo "$current_element" > $USER.start
	let current_element=$current_element+1
	echo "$current_element = $last_element"
	if [ "$current_element" = "$last_element" ]; then # if we have watched all the videos
		touch $USER.end
	fi
done






